[tool.black]
line-length = 79
target-version = ['py312']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ambassadors_project.settings_for_tests"
norecursedirs = "env/* venv/*"
addopts = [
    "-vv",
    "-p",
    "no:cacheprovider",
]
testpaths = "tests/"
python_files = "test_*.py"

[tool.isort]
src_paths = ["backend"]