[tool.black]
line-length = 89
target-version = ['py312']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backend.ambassadors_project.settings_for_tests"
norecursedirs = "env/* venv/*"
addopts = [
    "-vv",
    "-p",
    "no:cacheprovider",
]
testpaths = "backend/tests/"
python_files = "test_*.py"

[tool.isort]
known_third_party = [
    "venv/lib/*",
]