# Generated by Django 4.2.9 on 2024-02-26 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0003_alter_ambassadorsize_foot_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название продукции')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Стоимость не может быть отрицательной')], verbose_name='Стоимость продукции')),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерч',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_size', models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('Low', '35-39'), ('Medium', '39-41'), ('High', '41-44'), ('Large', '44-46')], null=True, verbose_name='Размер для одежды')),
                ('order_status', models.CharField(choices=[('создано', 'created'), ('доставлено', 'delivered'), ('отправлено', 'shipped')], default='создано', verbose_name='Размер для одежды')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('delivered_date', models.DateField(null=True, verbose_name='Дата получения заказа')),
                ('track_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Трек-номер')),
                ('comment', models.CharField(null=True, verbose_name='Комментарий к заявке')),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambassadors.ambassador', verbose_name='Получатель (амбассадор)')),
                ('merch', models.ManyToManyField(related_name='in_order', to='orders.merch', verbose_name='Мерч в заявке')),
            ],
            options={
                'verbose_name': 'Заявка на отправку мерча',
                'verbose_name_plural': 'Заявка на отправку мерча',
                'ordering': ('id',),
            },
        ),
    ]
