# Generated by Django 4.2.9 on 2024-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merch",
            name="name",
            field=models.CharField(
                choices=[
                    ("hoodie", "Толстовка"),
                    ("coffee", "Кофе"),
                    ("stikers", "Стикеры"),
                    ("yandex_plus", "Яндекс_плюс"),
                    ("arzamas", "Арзамас"),
                    ("shopper", "Шоппер"),
                    ("backpack", "Рюкзак"),
                    ("bag", "Сумка"),
                    ("socks", "Носки"),
                    ("discount", "Скидка"),
                    ("alice", "Алиса"),
                    ("alice_bot", "Алиса_бот"),
                    ("club", "Клуб"),
                ],
                max_length=60,
                verbose_name="Название продукции",
            ),
        ),
    ]
