# Generated by Django 4.2.9 on 2024-02-27 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_comment_alter_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ('name', 'size'), 'verbose_name': 'Мерч', 'verbose_name_plural': 'Мерч'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='merch_size',
        ),
        migrations.AddField(
            model_name='merch',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('Low', '35-39'), ('Medium', '39-41'), ('High', '41-44'), ('Large', '44-46')], null=True, verbose_name='Размер для одежды'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Стоимость не может быть отрицательной')], verbose_name='Полная стоимость продукции в заявке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке'),
        ),
    ]
