# Generated by Django 4.2.9 on 2024-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=20, verbose_name="Номер телефона"
            ),
        ),
    ]
