# Generated by Django 4.2.9 on 2024-03-10 16:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateField(
                default=datetime.date.today,
                verbose_name="Дата создания заявки",
            ),
        ),
    ]
