# Generated by Django 4.2.9 on 2024-02-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0003_alter_ambassadorsize_foot_size'),
        ('orders', '0004_alter_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambassadors.ambassadoraddress', verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
