# Generated by Django 4.2.9 on 2024-03-10 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата создания заявки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата получения заказа"
            ),
        ),
    ]
