# Generated by Django 4.2.9 on 2024-03-10 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_created_date_alter_order_delivered_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("created_date",),
                "verbose_name": "Заявка на отправку мерча",
                "verbose_name_plural": "Заявка на отправку мерча",
            },
        ),
    ]
