# Generated by Django 4.2.9 on 2024-02-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0004_alter_ambassador_middle_name'),
        ('orders', '0005_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ambassador',
        ),
        migrations.AddField(
            model_name='order',
            name='ambassador_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambassadors.ambassador', verbose_name='ID амбассадора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=11, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='post_index',
            field=models.IntegerField(default=1, verbose_name='Индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street_home',
            field=models.CharField(default=1, max_length=200, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tg_acc',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Телеграмм аккаунт'),
            preserve_default=False,
        ),
    ]
