# Generated by Django 4.2.9 on 2024-03-10 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_date",),
                "verbose_name": "Заявка на отправку мерча",
                "verbose_name_plural": "Заявка на отправку мерча",
            },
        ),
    ]
