# Generated by Django 4.2.9 on 2024-02-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0006_remove_order_address_remove_order_ambassador_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(
                max_length=200, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tg_acc",
            field=models.CharField(
                max_length=150, verbose_name="Телеграмм аккаунт"
            ),
        ),
    ]
