# Generated by Django 4.2.9 on 2024-03-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0004_alter_ambassador_middle_name'),
        ('orders', '0007_alter_order_email_alter_order_tg_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ambassador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ambassadors.ambassador', verbose_name='ID амбассадора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='merch',
            field=models.ManyToManyField(related_name='order', to='orders.merch', verbose_name='Мерч в заявке'),
        ),
    ]
