# Generated by Django 4.2.9 on 2024-03-10 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата отчета",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="link",
            field=models.URLField(
                unique=True, verbose_name="ссылка на контент"
            ),
        ),
    ]
