# Generated by Django 4.2.9 on 2024-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="document",
            field=models.URLField(
                max_length=400, verbose_name="Ссылка на документ"
            ),
        ),
    ]
