# Generated by Django 4.2.9 on 2024-02-28 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.CharField(max_length=2000, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Мужчина"), ("Female", "Женщина")],
                        max_length=20,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "tg_acc",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Телеграмм аккаунт",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        max_length=1500, verbose_name="Образование"
                    ),
                ),
                ("work_now", models.BooleanField(verbose_name="Работает")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Активный"),
                            ("Pause", "На паузе"),
                            ("Clarify", "Уточняется"),
                            ("Not active", "Не активный"),
                        ],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата и время создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбассадор",
                "verbose_name_plural": "Амбассадоры",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AmbassadorActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие амбассадора",
                "verbose_name_plural": "Действия амбассадоров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AmbassadorAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=100, verbose_name="Страна"),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Город"),
                ),
                (
                    "street_home",
                    models.CharField(max_length=200, verbose_name="Улица"),
                ),
                ("post_index", models.IntegerField(verbose_name="Индекс")),
            ],
            options={
                "verbose_name": "Адрес амбассадора",
                "verbose_name_plural": "Адреса амбассадоров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AmbassadorSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clothes_size",
                    models.CharField(
                        choices=[
                            ("XS", "Xs"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "Xl"),
                        ],
                        max_length=30,
                        verbose_name="Размер одежды",
                    ),
                ),
                (
                    "foot_size",
                    models.CharField(
                        choices=[
                            ("Low", "35-39"),
                            ("Medium", "39-41"),
                            ("High", "41-44"),
                            ("Large", "44-46"),
                        ],
                        max_length=30,
                        verbose_name="Размер обуви",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размеры амбассадора",
                "verbose_name_plural": "Размеры амбассадоров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MessageToAmbassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленное сообщение для амбассадора",
                "verbose_name_plural": "Отправленные сообщения для амбассадоров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SendingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.CharField(max_length=2000, verbose_name="Описание"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        null=True, verbose_name="Было отправлено"
                    ),
                ),
                (
                    "sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение для амбассадора",
                "verbose_name_plural": "Сообщения для амбассадоров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="YandexProgramm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="заголовок"),
                ),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ("id",),
            },
        ),
    ]
