# Generated by Django 4.2.9 on 2024-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="tg_acc",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Телеграмм аккаунт"
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorsize",
            name="clothes_size",
            field=models.CharField(
                choices=[
                    ("XS", "Xs"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "Xl"),
                ],
                max_length=30,
                verbose_name="Размер одежды",
            ),
        ),
        migrations.AlterField(
            model_name="sendingmessage",
            name="created",
            field=models.DateTimeField(
                null=True, verbose_name="Было отправлено"
            ),
        ),
        migrations.AlterField(
            model_name="yandexprogramm",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="yandexprogramm",
            name="title",
            field=models.CharField(max_length=300, verbose_name="заголовок"),
        ),
    ]
