# Generated by Django 4.2.9 on 2024-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="tg_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Телеграмм id"
            ),
        ),
    ]
