# Generated by Django 4.2.9 on 2024-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="purpose",
            field=models.CharField(
                max_length=300, null=True, verbose_name="цель обучения"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="education",
            field=models.CharField(max_length=300, verbose_name="Образование"),
        ),
    ]
