# Generated by Django 4.2.9 on 2024-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0003_ambassador_purpose_alter_ambassador_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Активный"),
                    ("Pause", "На паузе"),
                    ("Clarify", "Уточняется"),
                    ("Not active", "Не активный"),
                ],
                default="Clarify",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
