# Generated by Django 4.2.9 on 2024-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0003_ambassador_tg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="image",
            field=models.ImageField(
                default="profiles/default_pic.jpeg",
                null=True,
                upload_to="profiles/",
                verbose_name="Фото",
            ),
        ),
    ]
