# Generated by Django 4.2.9 on 2024-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0004_ambassador_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="tg_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="Телеграмм id"
            ),
        ),
    ]
