# Generated by Django 4.2.9 on 2024-03-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0005_alter_ambassador_tg_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="work_now",
        ),
        migrations.AddField(
            model_name="ambassador",
            name="work",
            field=models.CharField(
                blank=True, null=True, verbose_name="Работа"
            ),
        ),
    ]
