# Generated by Django 4.2.9 on 2024-03-09 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    models.TextField(max_length=2000, verbose_name="Текст"),
                ),
                (
                    "sent",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Дата отправки",
                    ),
                ),
                (
                    "by_email",
                    models.BooleanField(
                        default=False, verbose_name="На почту"
                    ),
                ),
                (
                    "to_telegram",
                    models.BooleanField(
                        default=False, verbose_name="В телеграм"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправить"
                    ),
                ),
                (
                    "ambassadors",
                    models.ManyToManyField(
                        related_name="messages", to="ambassadors.ambassador"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение для амбассадора",
                "verbose_name_plural": "Сообщения для амбассадоров",
                "ordering": ("id",),
            },
        ),
    ]
